spring.datasource.url= jdbc:mysql://localhost:3306/prem?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username= root
spring.datasource.password= Prem@1994
super.user.password= SuperPassword
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
debug= true

# App Properties
bezkoder.app.jwtSecret= bezKoderSecretKey
#bezkoder.app.jwtExpirationMs= 3600000
#bezkoder.app.jwtRefreshExpirationMs= 86400000

## For test
bezkoder.app.jwtExpirationMs= 6000000
bezkoder.app.jwtRefreshExpirationMs= 12000000
# 5 min
bezkoder.app.jwtMFAExpirationMs= 300000
